apiVersion: v1
description: 'Helm Chart to deploy the OpenStreetMap software'
name: microcosm
version: 0.1.1

dependencies:
- name: filebeat
  version: 7.10.0
  repository: https://helm.elastic.co
  condition: logging.enabled
  alias: filebeat-to-logstash
- name: filebeat
  version: 7.10.0
  repository: https://helm.elastic.co
  condition: logging.enabled
  alias: filebeat-to-elastic