apiVersion: v2
description: 'Helm Chart to deploy the OpenStreetMap software'
name: microcosm
version: 0.1.1
# List of sub chart that comprise this entire application
depedencies:
  - name: "db-geo"
    version: 0.1.0
  - name: "db-osm"
    version: 0.1.0
  - name: "jobs"
    version: 0.1.0
  - name: "osm-2-pgsql-mod-tile"
    version: 0.1.0
  - name: "tegola-imposm"
    version: 0.1.0
  - name: "web-osm"
    version: 0.1.0