{{- if and .Values.ingestion.enabled (ne .Values.cloudProvider.name "minikube") -}}
{{- with .Values.ingestion.pods.cgimap }}
{{- if and .enabled .route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-cgimap-route
  {{- if .route.timeout.enabled }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .route.timeout.duration }}
  {{- end }}
spec:
  path:  {{ .route.path }}
  to:
    kind: Service
    name: {{ $.Release.Name }}-cgimap
  {{ if .route.tls }}
  tls:
    termination: edge
  {{ end }}
{{- end -}}
{{- end -}}
{{- end -}}