{{- if and .Values.earthTiles.enabled .Values.earthTiles.pods.db.enabled -}}
{{- if .Values.earthTiles.pods.db.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-earth-tiles-db-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # {{- if eq .Values.cloudProvider.name  "aws" }}
  # storageClassName: {{ .Values.efs.storageClass }}
  # {{- end }}
  # {{- if eq .Values.cloudProvider.name  "minikube" }}
  # {{- end }}
  {{- if .Values.global.existingPV }}
  volumeName: {{ .Values.global.pvName }}
  storageClassName: ''
  {{- else }}
  # volumeName: {{ .Release.Name }}-earth-tiles-db-pv
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.earthTiles.pods.db.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.earthTiles.pods.db.persistenceDisk.storageSize }}
{{- end }}
{{- end }}