{{- if and .Values.vectorTiles.enabled .Values.vectorTiles.pods.imposm.enabled -}}
{{- if .Values.vectorTiles.pods.imposm.persistenceDisk.data.enabled -}}
## DATA PVC ##
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-imposm-data-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.global.existingPV }}
  volumeName: {{ .Values.global.pvName }}
  storageClassName: ''
  {{- else }}
  # volumeName: {{ .Release.Name }}-earth-tiles-db-pv
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.storageSize }}
{{- end }}
---
{{- if .Values.vectorTiles.pods.imposm.persistenceDisk.expired.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-imposm-expired-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.global.existingPV }}
  volumeName: {{ .Values.global.pvName }}
  storageClassName: ''
  {{- else }}
  # volumeName: {{ .Release.Name }}-earth-tiles-db-pv
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.storageSize }}
{{- end }}
{{- end }}