{{- if and .Values.vectorTiles.enabled .Values.vectorTiles.pods.imposm.enabled -}}
{{- if .Values.vectorTiles.pods.imposm.persistenceDisk.data.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-imposm-data-pv
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.storageSize }}
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: {{ .Values.efs.storageClass }} 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}:{{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.subPath }}
  {{- end }}
  # minikube provider
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ .Values.minikubeHostPath }}/{{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.subPath }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-imposm-data-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: {{ .Values.efs.storageClass }}
  {{- end }}
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ .Release.Name }}-imposm-data-pv
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.data.storageSize }}
{{- end }}
---
{{- if .Values.vectorTiles.pods.imposm.persistenceDisk.expired.enabled -}}
## expired PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-imposm-expired-pv
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.storageSize }}
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: {{ .Values.efs.storageClass }} 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}:{{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.subPath }}
  {{- end }}
  # minikube provider
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ .Values.minikubeHostPath }}/{{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.subPath }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-imposm-expired-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: {{ .Values.efs.storageClass }}
  {{- else }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ .Release.Name }}-imposm-expired-pv
  accessModes:
    - {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vectorTiles.pods.imposm.persistenceDisk.expired.storageSize }}
{{- end }}
{{- end }}