{{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.osm2pgsql.enabled -}}
{{- if .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-osm2pgsql-expired-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- else }}
  accessModes:
    - {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.accessMode }}
  resources:
    requests:
      # AWS Provider
      storage: {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.storageSize }}
{{- end }}
{{- end }}