{{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.osm2pgsql.enabled -}}
{{- if .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-osm2pgsql-pv
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.storageSize }}
  accessModes:
    - {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  {{- if eq .Values.cloudProvider.name "aws" }}
  storageClassName: {{ .Values.efs.storageClass }} 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}:{{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.subPath }}
  {{- end }}
  # minikube provider
  {{- if eq .Values.cloudProvider.name "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ .Values.minikubeHostPath }}/{{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.subPath }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-osm2pgsql-expired-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider.name "aws" }}
  storageClassName: {{ .Values.efs.storageClass }}
  {{- else }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ .Release.Name }}-osm2pgsql-pv
  accessModes:
    - {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.accessMode }}
  resources:
    requests:
      # AWS Provider
      storage: {{ .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.storageSize }}
{{- end }}
{{- end }}