{{- if and .Values.ingestion.enabled .Values.ingestion.pods.planetDump.enabled -}}
{{- if .Values.ingestion.pods.planetDump.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-planet-dump-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
{{- if .Values.global.existingPV }}
  selector:
    matchLabels:
      app: microcosm
  storageClassName: ''
  {{- else }}
  # volumeName: {{ .Release.Name }}-earth-tiles-db-pv
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  volumeName: {{ .Release.Name }}-planet-dump-pv
  accessModes:
    - {{ .Values.ingestion.pods.planetDump.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ingestion.pods.planetDump.persistenceDisk.storageSize }}
{{- end }}
{{- end }}