{{- if  and .Values.ingestion.enabled .Values.ingestion.pods.replicationJob.enabled -}}
{{- if .Values.ingestion.pods.replicationJob.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-replication-job-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.global.existingPV }}
  volumeName: {{ .Values.global.pvName }}
  storageClassName: ''
  {{- else }}
  # volumeName: {{ .Release.Name }}-earth-tiles-db-pv
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  volumeName: {{ .Release.Name }}-replication-job-pv
  accessModes:
    - {{ .Values.ingestion.pods.replicationJob.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ingestion.pods.replicationJob.persistenceDisk.storageSize }}
{{- end }}
{{- end }}