{{- if and .Values.ingestion.enabled .Values.ingestion.pods.replicationHttpServer.enabled -}}
{{- if .Values.ingestion.pods.replicationJob.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-replication-http-server-pv
  labels:
    app: {{ template "microcosm.name" . }}
    component: replicationHttpServer-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.storageSize }}
  accessModes:
    - {{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  storageClassName: {{ .Values.efs.storageClass }} 
  {{- if eq .Values.cloudProvider.name "aws" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}:{{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.subPath }}
  {{- end }}
  # minikube provider
  {{- if eq .Values.cloudProvider.name "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ .Values.minikubeHostPath }}/{{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.subPath }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-replication-http-server-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider.name "aws" }}
  storageClassName: {{ .Values.efs.storageClass }}
  {{- else }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ .Release.Name }}-replication-http-server-pv
  accessModes:
    - {{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ingestion.pods.replicationHttpServer.persistenceDisk.storageSize }}{{- end }}
{{- end }}