{{- $releaseName := .Release.Name -}}
{{- $name := include "microcosm.name" . -}}
{{- if  and .Values.ingestion.enabled .Values.ingestion.pods.replicationMerger.enabled -}}
{{- if $.Values.ingestion.pods.replicationMerger.persistenceDisk.enabled -}}
{{- range .Values.ingestion.pods.replicationMerger.timeUnits }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $releaseName }}-replication-merger-{{ .name }}-pv
  labels:
    app: {{ $name }}
    component: replicationMerger{{ .name | upper }}-pd
    environment: {{ $.Values.environment }}
    release: {{ $releaseName }}
spec:
  capacity:
    storage: {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.storageSize }}
  accessModes:
    - {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  storageClassName: {{ $.Values.efs.storageClass }} 
  {{- if eq $.Values.cloudProvider.name "aws" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ $.Values.efs.volumeHandle }}:{{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.subPath }}/{{ .name }}
  {{- end }}
  # minikube provider
  {{- if eq $.Values.cloudProvider.name "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ $.Values.minikubeHostPath }}/{{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.subPath }}/{{ .name }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $releaseName }}-replication-merger-{{ .name }}-pv-claim
  labels:
    app: {{ $name }}
    component: db-pd
    environment: {{ $.Values.environment }}
    release: {{ $releaseName }}
spec:
  {{- if eq $.Values.cloudProvider.name "aws" }}
  storageClassName: {{ $.Values.efs.storageClass }}
  {{- else }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ $releaseName }}-replication-merger-{{ .name }}-pv
  accessModes:
    - {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.storageSize }}
---
{{- end }}
{{- end }}
{{- end -}}