{{- $releaseName := .Release.Name -}}
{{- $name := include "microcosm.name" . -}}
{{- if  and .Values.ingestion.enabled .Values.ingestion.pods.replicationMerger.enabled -}}
{{- if $.Values.ingestion.pods.replicationMerger.persistenceDisk.enabled -}}
{{- range .Values.ingestion.pods.replicationMerger.timeUnits }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $releaseName }}-replication-merger-{{ .name }}-pv-claim
  labels:
    app: {{ $name }}
    component: db-pd
    environment: {{ $.Values.environment }}
    release: {{ $releaseName }}
spec:
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- else }}
  accessModes:
    - {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.storageSize }}
---
{{- end }}
{{- end }}
{{- end -}}