{{- if and .Values.vectorTiles.enabled .Values.vectorTiles.pods.db.enabled -}}
{{- if .Values.vectorTiles.pods.db.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vector-tiles-db-pv
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.vectorTiles.pods.db.persistenceDisk.storageSize }}
  accessModes:
    - {{ .Values.vectorTiles.pods.db.persistenceDisk.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  # AWS Provider
  storageClassName: {{ .Values.efs.storageClass }} 
  {{- if eq .Values.cloudProvider.name "aws" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}
  {{- end }}
  # minikube provider
  {{- if eq .Values.cloudProvider.name "minikube" }}
  storageClassName: ""
  hostPath:
    path: {{ .Values.minikubeHostPath }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vector-tiles-db-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider.name "aws" }}
  storageClassName: {{ .Values.efs.storageClass }}
  {{- else }}
  storageClassName: ''
  {{- end }}
  volumeName: {{ .Release.Name }}-vector-tiles-db-pv
  accessModes:
    - {{ .Values.vectorTiles.pods.db.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vectorTiles.pods.db.persistenceDisk.storageSize }}{{- end }}
{{- end }}