{{- if or .Values.vectorTilesDb.enabled (or .Values.tegola.enabled .Values.imposm.enabled)  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vector-tiles-db-configmap
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-db-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.vectorTilesDb.enabled -}}
  host: {{ .Release.Name }}-vector-tiles-db
  {{- else -}}
  host:  {{ .Values.vectorTilesDb.env.POSTGRES_HOST }}
  {{- end -}}
  database: {{ .Values.vectorTilesDb.env.POSTGRES_DB }}
{{- end }}