{{- if and .Values.ingestion.enabled (ne .Values.cloudProvider.name "minikube") -}}
{{- if and .Values.ingestion.pods.web.enabled .Values.ingestion.pods.cgimap.enabled -}}
{{- with .Values.ingestion.pods.webProxy }}
{{- if and .enabled .route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-web-proxy-route
spec:
  path:  {{ .route.path }}
  to:
    kind: Service
    name: {{ $.Release.Name }}-web-proxy
  {{- if .route.tls -}}
  tls:
    termination: edge
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}