{{- if or .Values.web.enabled .Values.webDb.enabled  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-configmap
  labels:
    app: {{ template "microcosm.name" . }}
    component: web-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.webDb.enabled -}}
  host: {{ .Release.Name }}-web-db
  {{- else -}}
  host:  {{ .Values.webDb.env.POSTGRES_HOST }}
  {{- end -}}
  database: {{ .Values.webDb.env.POSTGRES_DB }}
{{- end }}